name: subadmin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bubble_bottom_bar: ^2.0.0
  fluttertoast: ^8.2.1
  dotted_border: ^2.0.0+3
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.9
  # google_maps_place_picker: ^2.1.0-nullsafety.3
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^10.4.0
  dotted_line: ^3.1.0
  intl_phone_number_input: ^0.7.0+2
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  google_maps_place_picker_mb: ^3.0.1
  google_api_headers: ^1.3.0
  location: ^4.4.0
  package_info_plus_web: ^2.0.0
  geocoding: ^2.1.0
  change_app_package_name: ^1.1.0

  
  dio: ^5.0.3
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  get_it: ^7.2.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.8.0
  intl: ^0.18.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.20
  socket_io_client: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
